const fs = require('fs');
const path = require('path');
const logger = require('./logger');

const MD_FILE = path.resolve(__dirname, '..', 'intern.md');
const HEADER = '# 🎯 Filtered Internship Messages\n\n_Auto-generated by Intern Bot (Strict Batch Filter)_\n\n---\n\n';

/**
 * Ensure the Markdown file exists with a header.
 */
function ensureFile() {
  if (!fs.existsSync(MD_FILE)) {
    fs.writeFileSync(MD_FILE, HEADER, 'utf-8');
    logger.info(`Created ${MD_FILE}`);
  }
}

/**
 * Read the current Markdown file content.
 */
function readFile() {
  ensureFile();
  return fs.readFileSync(MD_FILE, 'utf-8');
}

/**
 * Check if the message ID already exists in the file.
 */
function isMessageDuplicate(messageId) {
  const content = readFile();
  return content.includes(`### Message #${messageId}`);
}

/**
 * Append a raw message to intern.md if it matches the batch.
 * @param {object} message
 * @param {string} reason - AI provided explanation
 */
function appendFilteredRawMessage(message, reason) {
  ensureFile();

  if (isMessageDuplicate(message.id)) {
    logger.warn(`Message #${message.id} is already in intern.md. Skipping.`);
    return false;
  }

  const timestamp = message.date ? message.date.toISOString() : new Date().toISOString();
  
  let block = '';
  block += `### Message #${message.id} (${timestamp})\n`;
  block += `> **AI Filter Note:** ${reason}\n\n`;
  block += `${message.text}\n\n`;
  block += '---\n\n';

  fs.appendFileSync(MD_FILE, block, 'utf-8');
  logger.success(`Saved matching message #${message.id} to intern.md`);
  return true;
}

module.exports = { appendFilteredRawMessage, isMessageDuplicate, ensureFile, MD_FILE };
