const fs = require('fs');
const path = require('path');
const logger = require('./logger');

const MD_FILE = path.resolve(__dirname, '..', 'internships.md');
const HEADER = '# 📋 Internship Database\n\n_Auto-generated by Intern Bot_\n\n---\n\n';

/**
 * Ensure the Markdown file exists with a header.
 */
function ensureFile() {
  if (!fs.existsSync(MD_FILE)) {
    fs.writeFileSync(MD_FILE, HEADER, 'utf-8');
    logger.info(`Created ${MD_FILE}`);
  }
}

/**
 * Read the current Markdown file content.
 */
function readFile() {
  ensureFile();
  return fs.readFileSync(MD_FILE, 'utf-8');
}

/**
 * Check whether an internship with the same company AND apply_link
 * already exists in the Markdown file.
 */
function isDuplicate(company, applyLink) {
  const content = readFile();

  const normalise = (s) => (s || '').trim().toLowerCase();

  // Quick heuristic: look for both the company heading and the link in proximity
  const companyNorm = normalise(company);
  const linkNorm    = normalise(applyLink);

  if (!companyNorm && !linkNorm) return false;

  // Split into entry blocks separated by the "---" delimiter
  const blocks = content.split(/^---$/m);

  for (const block of blocks) {
    const blockLower = block.toLowerCase();
    const hasCompany = companyNorm ? blockLower.includes(companyNorm) : true;
    const hasLink    = linkNorm   ? blockLower.includes(linkNorm)    : true;
    if (hasCompany && hasLink) return true;
  }

  return false;
}

/**
 * Format a single internship object into a Markdown block.
 */
function formatInternship(internship) {
  const val = (v) => (v && v.trim ? v.trim() : null) || 'Not provided';

  let block = '';
  block += `## Company: ${val(internship.company)}\n\n`;
  block += `**Domain:** ${val(internship.domain)}  \n`;
  block += `**Stipend:** ${val(internship.stipend)}  \n`;
  block += `**Apply Link:** ${val(internship.apply_link)}  \n`;
  block += `**Email:** ${val(internship.email)}  \n`;
  block += '\n---\n\n';

  return block;
}

/**
 * Append an internship to the Markdown file (with duplicate check).
 *
 * @returns {boolean} true if appended, false if skipped as duplicate
 */
function appendInternship(internship) {
  ensureFile();

  if (isDuplicate(internship.company, internship.apply_link)) {
    logger.warn(
      `Duplicate skipped: ${internship.company || 'Unknown'} — ${internship.apply_link || 'no link'}`
    );
    return false;
  }

  const block = formatInternship(internship);
  fs.appendFileSync(MD_FILE, block, 'utf-8');
  logger.success(`Appended: ${internship.company || 'Unknown Company'}`);
  return true;
}

const RAW_FILE = path.resolve(__dirname, '..', 'raw_messages.md');
const RAW_HEADER = '# 📜 Raw Telegram Messages\n\n_Auto-generated by Intern Bot_\n\n---\n\n';

/**
 * Ensure the Raw messages file exists.
 */
function ensureRawFile() {
  if (!fs.existsSync(RAW_FILE)) {
    fs.writeFileSync(RAW_FILE, RAW_HEADER, 'utf-8');
    logger.info(`Created ${RAW_FILE}`);
  }
}

/**
 * Append a raw Telegram message text to the Markdown file.
 */
function appendRawMessage(message) {
  ensureRawFile();

  const timestamp = message.date ? message.date.toISOString() : new Date().toISOString();
  const block = `### Message #${message.id} (${timestamp})\n\n${message.text}\n\n---\n\n`;

  fs.appendFileSync(RAW_FILE, block, 'utf-8');
  logger.success(`Saved raw message #${message.id}`);
}

module.exports = { appendInternship, appendRawMessage, isDuplicate, formatInternship, readFile, ensureFile, MD_FILE };
